minor formatting and text updates
redhat-developer/app-services-guides pull request #402
Opened 2022-02-11 17:28 UTC by fmcdonal

2022-02-11 17:30 UTC, wtrocki commented
Looks good!

2022-02-14 10:16 UTC, jbyrne-redhat commented on docs/kafka/nodejs/README.adoc
> +You should see see the Node.js run and connect to the Kafka instance. However, because you haven't yet run the producer component, the consumer has no country names to display.
@fmcdonal Repeat of the word 'see' here.

Also, it should read: "You should see the Node.js _application_ run...". This one is my fault :) I wrote it incorrectly in the JIRA, which I just updated.

2022-02-14 10:17 UTC, jbyrne-redhat requested changes
Looks great, @fmcdonal  - just two very minor updates to request.

2022-02-15 17:50 UTC, fmcdonal commented
@jbyrne-redhat changes applied

2022-02-15 18:40 UTC, jbyrne-redhat approved these changes
Looks great, @fmcdonal  - thanks! Ready to merge.

2022-02-16 11:29 UTC, merged